# Generated by Django 2.0.4 on 2019-09-02 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QoSmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessapp',
            name='name',
            field=models.CharField(max_length=45),
        ),
    ]
