# Generated by Django 2.0.4 on 2019-09-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QoSmanager', '0003_auto_20190903_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='mark',
            field=models.CharField(choices=[('CS7', 'CS7'), ('CS6', 'CS6'), ('EF', 'EF'), ('CS5', 'CS5'), ('AF43', 'AF43'), ('AF42', 'AF42'), ('AF41', 'AF41'), ('CS4', 'CS4'), ('AF33', 'AF33'), ('AF32', 'AF32'), ('AF31', 'AF31'), ('CS3', 'CS3'), ('AF23', 'AF23'), ('AF22', 'AF22'), ('AF21', 'AF21'), ('CS2', 'CS2'), ('AF13', 'AF13'), ('AF12', 'AF12'), ('AF11', 'AF11'), ('CS1', 'CS1'), ('DEFAULT', 'DEFAULT')], max_length=20),
        ),
    ]
