# Generated by Django 2.0.4 on 2020-04-17 17:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('QoSmanager', '0004_auto_20190903_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='deploy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='regroupementclass',
            name='bits',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tuninghistory',
            name='policy_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='QoSmanager.Policy'),
        ),
        migrations.AddField(
            model_name='tuninghistory',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='access',
            name='enable_secret',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='access',
            name='management_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='access',
            name='management_interface',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='access',
            name='password',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='access',
            name='username',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='begin_time',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='custom_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='destination',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='end_time',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='mark',
            field=models.CharField(choices=[('RECOMMENDED', 'RECOMMENDED'), ('CS6', 'CS6'), ('EF', 'EF'), ('CS5', 'CS5'), ('AF43', 'AF43'), ('AF42', 'AF42'), ('AF41', 'AF41'), ('CS4', 'CS4'), ('AF33', 'AF33'), ('AF32', 'AF32'), ('AF31', 'AF31'), ('CS3', 'CS3'), ('AF23', 'AF23'), ('AF22', 'AF22'), ('AF21', 'AF21'), ('CS2', 'CS2'), ('AF13', 'AF13'), ('AF12', 'AF12'), ('AF11', 'AF11'), ('CS1', 'CS1'), ('DEFAULT', 'DEFAULT')], default='RECOMMENDED', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='port_number',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='protocol_type',
            field=models.CharField(choices=[('ip', 'ip'), ('tcp', 'tcp'), ('udp', 'udp')], default='ip', max_length=255),
        ),
        migrations.AlterField(
            model_name='application',
            name='source',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='businessapp',
            name='match',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='businessapp',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='businessapp',
            name='recommended_dscp',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='businesstype',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='hostname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='device',
            name='policy_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QoSmanager.Policy'),
        ),
        migrations.AlterField(
            model_name='dscp',
            name='denominator',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dscp',
            name='drop_max',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dscp',
            name='drop_max_new',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dscp',
            name='drop_max_old',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dscp',
            name='drop_min',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dscp',
            name='drop_min_new',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dscp',
            name='drop_min_old',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dscp',
            name='dscp_value',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='group',
            name='priority',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='interface',
            name='interface_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='interface',
            name='policy_out_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='QoSmanager.PolicyOut'),
        ),
        migrations.AlterField(
            model_name='policing',
            name='cir',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='policing',
            name='dscp_transmit',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='policing',
            name='pir',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='policy',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='policy',
            name='name',
            field=models.CharField(error_messages={'unique': 'this name is in used'}, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='regroupementclass',
            name='bandwidth',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='regroupementclass',
            name='priority',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shaping',
            name='average',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='shaping',
            name='peak',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='topology',
            name='topology_desc',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='topology',
            name='topology_name',
            field=models.CharField(max_length=255),
        ),
    ]
